[package]
name = "quick-pickle"
version = "0.1.0"
edition = "2024"

[dependencies]
atoi = "2.0.0"
orx-parallel = "3.3.0"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "bench"
harness = false
